default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: <%= ENV['RAILS_MYSQL_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_MYSQL_DATABASE_PASSWORD'] || 'root' %>
  host: <%= ENV['RAILS_MYSQL_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['RAILS_MYSQL_DATABASE_PORT'] || '3306' %>

development:
  <<: *default
  database: stock_app_development
  socket: <%= ENV['RAILS_MYSQL_DATABASE_SOCKET'] || '/tmp/mysql.sock'%>

test:
  <<: *default
  database: stock_app_test
  socket: <%= ENV['RAILS_MYSQL_DATABASE_SOCKET'] %>

production:
  <<: *default
  database: stock_app_production
  username: <%= ENV['RAILS_MYSQL_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS_MYSQL_DATABASE_PASSWORD'] %>
  host    : <%= ENV['RAILS_MYSQL_DATABASE_HOST'] %>
  port    : <%= ENV['RAILS_MYSQL_DATABASE_PORT'] %>